/* 750TH */

#define BOARD_PID		"750TH"
#define BOARD_NAME		"750TH"
#define BOARD_DESC		"HiWiFi 750TH Wireless Router"
#define BOARD_VENDOR_NAME	"HiWiFi"
#define BOARD_VENDOR_URL	"http://www.hiwifi.com/"
#define BOARD_MODEL_URL		"http://www.hiwifi.com/"
#define BOARD_BOOT_TIME		25
#define BOARD_FLASH_TIME	120
#define BOARD_GPIO_BTN_RESET	12
#define BOARD_GPIO_LED_INVERTED
#undef  BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#define BOARD_GPIO_LED_SW2G	6
#define BOARD_GPIO_LED_SW5G	7
#define BOARD_GPIO_LED_POWER	9
#undef  BOARD_GPIO_LED_LAN
#define BOARD_GPIO_LED_WAN	11
#undef  BOARD_GPIO_LED_USB
#undef  BOARD_GPIO_LED_ROUTER
#define BOARD_HAS_5G_11AC	1
#define BOARD_NUM_ANT_5G_TX	1
#define BOARD_NUM_ANT_5G_RX	1
#define BOARD_NUM_ANT_2G_TX	2
#define BOARD_NUM_ANT_2G_RX	2
#define BOARD_NUM_ETH_LEDS	1
#define BOARD_GPIO_PWR_USB	41
#define BOARD_GPIO_PWR_USB_ON	0
#define BOARD_HAS_EPHY_L1000	0
#define BOARD_HAS_EPHY_W1000	0
